version: "3.9"

services:

  jgitkins-web:
    image: ghcr.io/jgitkins/jgitkins-web:latest
    ports:
      - "18081:8081"
    environment:
      REDIS_HOST: valkey
      REDIS_PORT: "6379"
      JGITKINS_SERVER_BASE_URL: http://jgitkins-server:8084
    networks:
      - jgitkins-net
    restart: unless-stopped

  # nginx:
  #   image: nginx:stable
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - /opt/apps/nginx/nginx/conf.d/reverse.conf:/etc/nginx/conf.d/reverse.conf:ro
  #   networks:
  #     - jgitkins-net
  #   restart: unless-stopped

networks:
  jgitkins-net:
    external: true
