version: "3.9"

services:
  jgitkins-web:
    build:
      context: ../..
      dockerfile: Dockerfile
    image: ghcr.io/jgitkins/jgitkins-web:latest
    ports:
      - "18081:8081"
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SOPS_AGE_KEY_FILE: /opt/apps/jgitkins/config/sops/age/keys.txt
#      JGITKINS_SERVER_BASE_URL: http://jgitkins-server:8084 # TODO: remove
    volumes:
      - /opt/apps/jgitkins/config/sops/age/keys.txt:/opt/apps/jgitkins/config/sops/age/keys.txt
    networks:
      - jgitkins-net
    restart: unless-stopped

networks:
  jgitkins-net:
    external: true
